name: "Test application"

on:
    pull_request:
    push:
        branches:
            - "master"
            - "[0-9]+.x"
            - "[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+.x"

jobs:
    test:
        name: "PHP ${{ matrix.php-version }}, Symfony ${{ matrix.symfony-require }} ${{ matrix.dependencies }}"
        runs-on: "ubuntu-20.04"
        env:
            SYMFONY_DEPRECATIONS_HELPER: weak

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: "7.2"
                      dependencies: "lowest"
                      symfony-require: "4.4.*"

                    - php-version: "7.4"
                      symfony-require: "4.4.*"

                    - php-version: "7.4"
                      symfony-require: "5.0.*"

                    - php-version: "8.0"
                      phpunit-version: "9.0"
                      symfony-require: "*"

        steps:
            - name: "Checkout project"
              uses: "actions/checkout@v2"

            - name: "Install and configure PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: "pdo, pdo_sqlite"
                  tools: "composer:v2"

            - name: "Require Specific Symfony Version"
              if: "${{ matrix.symfony-version }}"
              run: "composer require --no-update symfony/symfony:${{ matrix.symfony-version }}"

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"
                  composer-options: "--prefer-dist"

            - name: "Execute test cases"
              run: |
                if [[ $SYMFONY_PHPUNIT_VERSION == '' ]]; then unset SYMFONY_PHPUNIT_VERSION; fi;
                make test
              env:
                  SYMFONY_PHPUNIT_VERSION: "${{ matrix.phpunit-version }}"
